// <auto-generated />
using System;
using GerenciadorDeAcervos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GerenciadorDeAcervos.Migrations
{
    [DbContext(typeof(AcervoDbContext))]
    [Migration("20230918183916_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GerenciadorDeAcervos.Data.Models.Colecao", b =>
                {
                    b.Property<int>("ColecaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColecaoId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SetorId")
                        .HasColumnType("int");

                    b.HasKey("ColecaoId");

                    b.HasIndex("SetorId");

                    b.ToTable("Colecoes");
                });

            modelBuilder.Entity("GerenciadorDeAcervos.Data.Models.Instituicao", b =>
                {
                    b.Property<int>("InstituicaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstituicaoId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstituicaoId");

                    b.ToTable("Instituicao");
                });

            modelBuilder.Entity("GerenciadorDeAcervos.Data.Models.Objeto", b =>
                {
                    b.Property<int>("ObjetoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObjetoId"));

                    b.Property<int>("ColecaoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ObjetoId");

                    b.HasIndex("ColecaoId");

                    b.ToTable("Objetos");
                });

            modelBuilder.Entity("GerenciadorDeAcervos.Data.Models.Permissao", b =>
                {
                    b.Property<int>("PermissaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissaoId"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NivelPermissao")
                        .HasColumnType("int");

                    b.HasKey("PermissaoId");

                    b.ToTable("Permissoes");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Permissao");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GerenciadorDeAcervos.Data.Models.Setor", b =>
                {
                    b.Property<int>("SetorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SetorId"));

                    b.Property<int>("InstituicaoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SetorId");

                    b.HasIndex("InstituicaoId");

                    b.ToTable("Setores");
                });

            modelBuilder.Entity("GerenciadorDeAcervos.Data.Models.Usuario", b =>
                {
                    b.HasBaseType("GerenciadorDeAcervos.Data.Models.Permissao");

                    b.Property<byte[]>("Imagem")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(max)")
                        .HasDefaultValue(new byte[0]);

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsuarioNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Usuario");
                });

            modelBuilder.Entity("GerenciadorDeAcervos.Data.Models.Colecao", b =>
                {
                    b.HasOne("GerenciadorDeAcervos.Data.Models.Setor", "Setor")
                        .WithMany("Colecoes")
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("GerenciadorDeAcervos.Data.Models.Objeto", b =>
                {
                    b.HasOne("GerenciadorDeAcervos.Data.Models.Colecao", "Colecao")
                        .WithMany("Objetos")
                        .HasForeignKey("ColecaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colecao");
                });

            modelBuilder.Entity("GerenciadorDeAcervos.Data.Models.Setor", b =>
                {
                    b.HasOne("GerenciadorDeAcervos.Data.Models.Instituicao", "Insituicao")
                        .WithMany("Setores")
                        .HasForeignKey("InstituicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insituicao");
                });

            modelBuilder.Entity("GerenciadorDeAcervos.Data.Models.Usuario", b =>
                {
                    b.HasOne("GerenciadorDeAcervos.Data.Models.Permissao", "Permissao")
                        .WithMany()
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permissao");
                });

            modelBuilder.Entity("GerenciadorDeAcervos.Data.Models.Colecao", b =>
                {
                    b.Navigation("Objetos");
                });

            modelBuilder.Entity("GerenciadorDeAcervos.Data.Models.Instituicao", b =>
                {
                    b.Navigation("Setores");
                });

            modelBuilder.Entity("GerenciadorDeAcervos.Data.Models.Setor", b =>
                {
                    b.Navigation("Colecoes");
                });
#pragma warning restore 612, 618
        }
    }
}
