// <auto-generated />
using System;
using GerenciadorDeAcervos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GerenciadorDeAcervos.Migrations
{
    [DbContext(typeof(AcervoDbContext))]
    [Migration("20230824180718_acervodb")]
    partial class acervodb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GerenciadorDeAcervos.Data.Models.Colecao", b =>
                {
                    b.Property<int>("ColecaoId")
                        .HasColumnType("int");

                    b.Property<int>("ColecoesId")
                        .HasColumnType("int");

                    b.ToTable("Colecao");
                });

            modelBuilder.Entity("GerenciadorDeAcervos.Data.Models.Colecoes", b =>
                {
                    b.Property<int>("ColecoesId")
                        .HasColumnType("int");

                    b.Property<int>("SetorId")
                        .HasColumnType("int");

                    b.ToTable("Colecoes");
                });

            modelBuilder.Entity("GerenciadorDeAcervos.Data.Models.Objetos", b =>
                {
                    b.Property<int>("ColecaoId")
                        .HasColumnType("int");

                    b.Property<int>("ObjetoId")
                        .HasColumnType("int");

                    b.ToTable("Objetos");
                });

            modelBuilder.Entity("GerenciadorDeAcervos.Data.Models.Permissoes", b =>
                {
                    b.Property<int>("ColecaoId")
                        .HasColumnType("int");

                    b.Property<int>("NivelPermissao")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ObjetoId")
                        .HasColumnType("int");

                    b.Property<int>("PermissaoId")
                        .HasColumnType("int");

                    b.Property<int>("SetorId")
                        .HasColumnType("int");

                    b.ToTable("Permissoes");
                });

            modelBuilder.Entity("GerenciadorDeAcervos.Data.Models.Setor", b =>
                {
                    b.Property<int>("SetorId")
                        .HasColumnType("int");

                    b.ToTable("Setores");
                });

            modelBuilder.Entity("GerenciadorDeAcervos.Data.Models.Usuario", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Imagem")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(max)")
                        .HasDefaultValue(new byte[0]);

                    b.Property<int>("NivelPermissao")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
